import fetch from "node-fetch";
import "dotenv/config";

const generateParseDate = (  ) =>  "/Date(" + Date.parse( new Date(  ) ) + ")/";

const updateTestCaseTestRun =  async ( inputDate ) => {
    const endpointGetTestSteps = "https://alm-itac.spiraservice.net/services/v5_0/RestService.svc/projects/" + inputDate.idProject +"/test-cases/" + inputDate.idTestCase + 
    "/test-steps?username=" + process.env.USER_NAME + "&api-key={" + process.env.API_KEY + "}";
    const responseBodyTestSteps =  await fetch( endpointGetTestSteps, {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        }
    });
    return responseBodyTestSteps.json(  );
};

function callFunctionUpdateTestRun( inputDate, countStepsFailed = 0 ) {
    try {
        if( !inputDate.idProject ) {
            throw "El parámetro idProject es requerido.";
        } else if( !inputDate.idRelease ) {
            throw "El parámetro idRelease es requerido.";
        } else if( !inputDate.idTestCase ) {
            throw "El parámetro idTestCase es requerido.";
        } else if( !inputDate.idTestSet ) {
            throw "El parámetro idTestSet es requerido.";
        } else {
            updateTestCaseTestRun( inputDate ).then( async ( arraySteps ) => {
                arraySteps[0].ConcurrencyDate = generateParseDate(  );
                arraySteps[0].LastUpdateDate = generateParseDate(  );
                ( countStepsFailed > 0 ) ? arraySteps[0].ExecutionStatusId = 1 : arraySteps[0].ExecutionStatusId = 2;
                const endpointUpdateTestRun = "https://alm-itac.spiraservice.net/services/v5_0/RestService.svc/projects/37/test-runs?end_date=&username=" + process.env.USER_NAME + 
                "&api-key={" + process.env.API_KEY + "}";
                console.log( await fetch( endpointUpdateTestRun, {
                    method: "PUT",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify( [{
                        "ArtifactTypeId": 5,
                        "ConcurrencyDate": generateParseDate(  ),
                        "CustomProperties": [],
                        "IsAttachments": false,
                        "ProjectId": inputDate.idProject,
                        "ActualDuration": 0,
                        "BuildId": null,
                        "EndDate": generateParseDate(  ),
                        "EstimatedDuration": null,
                        "ExecutionStatusId": ( countStepsFailed > 0 ) ? 1 : 2,
                        "Name": "Test run generated by Cypress",
                        "ReleaseId": inputDate.idRelease,
                        "StartDate": generateParseDate(  ),
                        "TestCaseId": inputDate.idTestCase,
                        "TestRunTypeId": 1,
                        "TestSetId": inputDate.idTestSet,
                        "TestSetTestCaseId": null,
                        "TesterId": 25,
                        "TestRunSteps": arraySteps
                    } ])
                } ))
            } );
        }
    } catch( error ) {
        console.log( "Error: " + error );
    } finally {
        console.log( "Proceso de validación del TestCase finalizado" );
    }
}

module.exports = {
    callFunctionUpdateTestRun
}